name: 'webservices-dispatch-action'
description: 'conda-forge webservices dispatch GitHub Action'
author: conda-forge core (@conda-forge/core)
inputs:
  github_token:
    description: 'github token'
    required: true
runs:
  using: 'docker'
  image: 'docker://condaforge/webservices-dispatch-action:dev'
  args:
    - ${{ inputs.github_token }}
