#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

source /opt/conda/etc/profile.d/conda.sh

conda config --set show_channel_urls True
conda config --add channels conda-forge
conda config --show-sources
conda config --set always_yes yes
conda config --set channel_priority strict

conda activate base

conda update conda-smithy conda-forge-pinning conda-build -y --quiet

conda info

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

python /opt/conda-forge/rerender.py
