#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

git config --global user.name "conda-forge-webservices[bot]"
git config --global user.email "91080706+conda-forge-webservices[bot]@users.noreply.github.com"

source /opt/conda/etc/profile.d/conda.sh
micromamba activate base

micromamba update --all --yes

micromamba info
micromamba list

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

run-webservices-dispatch-action
